### Create user
POST localhost:8080/users
Content-Type: application/json

{
  "name": "TestUser"
}

### Retrieve user by id obtained from create user response
GET localhost:8080/users/598882a7-0fd3-49a1-9a46-89dd70a58209
Accept: application/json


