### Create user
POST localhost:8080/users
Content-Type: application/json

{
  "name": "TestUser"
}

### Retrieve user by id obtained from create user response
GET localhost:8080/users/31cc4f08-b887-453d-9019-2daec3cb504f
Accept: application/json


